# Generated by Django 5.2.4 on 2026-01-22 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed_name', models.CharField(max_length=50)),
                ('comment', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Paddock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paddock_name', models.CharField(max_length=20)),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('status', models.BooleanField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kupe_no', models.CharField(max_length=20, unique=True)),
                ('rfid_no', models.CharField(max_length=20, unique=True)),
                ('gender', models.CharField(choices=[('e', 'Erkek'), ('d', 'Dişi')], max_length=1)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('breed_no', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hayvanlar.breed', verbose_name='Irkı')),
                ('paddock_no', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hayvanlar.paddock')),
            ],
            options={
                'verbose_name': 'Hayvan',
                'verbose_name_plural': 'Hayvanlar',
            },
        ),
        migrations.CreateModel(
            name='WeightRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Ağırlık (kg)')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Tarım Tarihi')),
                ('animal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weights', to='hayvanlar.animal', verbose_name='Hayvan')),
            ],
            options={
                'verbose_name': 'Tartım Kaydı',
                'verbose_name_plural': 'Tartım Kayıtları',
                'ordering': ['-date'],
            },
        ),
    ]
